### PR TITLE
plugin: Upgrade to cap v3

### PR DESCRIPTION
**Pull request by hemangsk**

### CODE REVIEW

**Comment by hemangsk** [comment]
@aacassandra, we're working on updating the install guide. Right now you can install the v3 branch directly via github repo

```
npm install git://github.com/capacitor-community/capacitor-googlemaps-native.git#v3 --save
```

**Comment by aacassandra** [comment]
hey @hemangsk, i installed this in v3 branch. how do i use this in capacitor v3. isn't the function const {CapacitorGoogleMaps} = Plugins; "Plugins" from the capacitor/core is outdated. how do i get the CapacitorGoogleMaps in capacitor 3. can i use as below?:

import {CapacitorGoogleMaps} from '' capacitor-googlemaps-native "

like other capacitor v3 plugins. new way almost using like this and not using " const {} = Plugins"

**Comment by hemangsk** [comment]
Looking into it, ``` import {CapacitorGoogleMaps} from ''@capacitor-community/capacitor-googlemaps-native " ``` should work but it isn't working for some reason.

**Comment by hemangsk** [comment]
@aacassandra This works now,

Install from master (it has v3 support merged now),
```
npm i -S git+https://github.com/capacitor-community/capacitor-googlemaps-native
```

and 

```
import { CapacitorGoogleMaps } from '@capacitor-community/capacitor-googlemaps-native';
```

**Comment by aacassandra** [comment]
wow that looks great, ok i will try it later and will update my try soon

**Comment by hemangsk** [comment]
@aacassandra I'm not familiar with vue,  but see this example if it helps,

If we do something like,
```
CapacitorGoogleMaps.create({
      width:100,
      height: 300,
      x: 10,
      y: 20,
      latitude: -33.86,
      longitude: 151.20,
      zoom: 12
    })
```
Then the plugin will draw a map on top left of the screen (and the precise coordinates will be (10,20)). The map's dimensions would be 100x300. Done, and then you don't have to really care about boundingRect stuff in the angular example.

**Comment by aacassandra** [comment]
what is the function of this element <div id="map" #map></div> on angular?

does CapacitorGoogleMaps.create need to be attached to that element to bring up the map? or by using CapacitorGoogleMaps.create it automatically calls the native pagemap?

**Comment by hemangsk** [comment]
CapacitorGoogleMaps.create just needs the 
1. starting x,y coordinate of the map view, and 
2. height and width of the map view. 

<div id="map" #map>  is used to draw and HTML element on DOM, and then DOMRect() thing grabs the x,y coordinate, height and width of this div.

**Pull request merged**
